DonorInformation/Models/Donor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace DonorInformation.Models
{
    public class Donor
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Required")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Required")]
        public string Address { get; set; }

        [Required(ErrorMessage ="Required")]
        public int Mobile { get; set; }

        [Required(ErrorMessage ="Required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage ="Required")]     
        public int groupId { get; set; }

        [NotMapped]
        [Display(Name = "Blood Group")]
        public string BloodGroup { get; set; }
    }
}

DonorInformation/Models/DonorContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DonorInformation.Models
{
    public class DonorContext: DbContext
    {
        public DonorContext(DbContextOptions<DonorContext> options):base(options)
        {

        }
        public DbSet<Donor> Donor { get; set; }
        public DbSet<Group> BloodGroup { get; set; }
    }
}

DonorInformation/Models/ErrorViewModel.cs
using System;

namespace DonorInformation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DonorInformation/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DonorInformation.Models
{
    public class Group
    {
        [Key]
        public int groupId { get; set; }

        public string BloodGroup { get; set; }
    }
}

DonorInformation/Controllers/DonorController.cs
using DonorInformation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DonorInformation.Controllers
{
    public class DonorController : Controller
    {
        private readonly DonorContext _Db;
        public DonorController(DonorContext Db)
        {
            _Db = Db;
        }
        public IActionResult DonorList()
        {
           
            try
            {
                //var donorList = _Db.Donor.ToList();

                var donorList = from a in _Db.Donor
                                join b in _Db.BloodGroup
                                on a.groupId equals b.groupId
                                into Grp
                                from b in Grp.DefaultIfEmpty()

                                select new Donor
                                {
                                    Id = a.Id,
                                    Name=a.Name,
                                    Address=a.Address,
                                    Mobile=a.Mobile,
                                    Email=a.Email,
                                    groupId=a.groupId,

                                    BloodGroup=b==null?"":b.BloodGroup

                                };
                              


                return View(donorList);
            }
            catch (Exception ex)
            {

                return View();
            }
           
        }

        public IActionResult Create(Donor obj)
        {
            loadDDL();
            return View(obj);
        }
        
        [HttpPost]
        public async Task<IActionResult> AddDonor(Donor obj)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    if (obj.Id == 0)
                    {
                        _Db.Donor.Add(obj);
                        await _Db.SaveChangesAsync();
                    }
                    else
                    {
                        _Db.Entry(obj).State = EntityState.Modified;
                        await _Db.SaveChangesAsync();
                    }
                   
                    return RedirectToAction("DonorList");
                }
                

                return View();
            }
            catch (Exception ex)
            {


                return RedirectToAction("DonorList");
            }
        }

        public async Task<IActionResult> DeleteDnr(int Id)
        {
            try
            {
                var dnr = await _Db.Donor.FindAsync(Id);
                if(dnr!=null)
                {
                    _Db.Donor.Remove(dnr);
                    await _Db.SaveChangesAsync();
                }


                return RedirectToAction("DonorList");
            }
            catch (Exception ex)
            {

                return RedirectToAction("DonorList");
            }
        }

        private void loadDDL()
        {
            try
            {
                List<Group> grpList = new List<Group>();
                grpList = _Db.BloodGroup.ToList();

                grpList.Insert(0, new Group { groupId = 0, BloodGroup = "Please Select" });

                ViewBag.GrpList = grpList;
            }
            catch (Exception ex)
            {

              
            }
        }
    }
}

DonorInformation/Controllers/HomeController.cs
using DonorInformation.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DonorInformation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DonorInformation/Views/Donor/Create.cshtml
@model DonorInformation.Models.Donor

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Donor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddDonor">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <input type="hidden" asp-for="Id" />
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BloodGroup" class="control-label"></label>
                <select asp-for="groupId" class="form-control"asp-items="@(new SelectList(ViewBag.GrpList,"groupId","BloodGroup"))">
                   
                </select>
            </div>
                <div class="form-group">
                    <label asp-for="Address" class="control-label"></label>
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Mobile" class="control-label"></label>
                    <input asp-for="Mobile" class="form-control" />
                    <span asp-validation-for="Mobile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="DonorList" class="btn btn-outline-success">Donor List</a>
                </div>
</form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DonorInformation/Views/Donor/DonorList.cshtml
@model IEnumerable<DonorInformation.Models.Donor>

@{
    ViewData["Title"] = "DonorList";
}

<h1>Donor List</h1>

<p class="float-right">
    <a asp-action="Create" class="btn btn-outline-primary">Add New</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BloodGroup)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>Action</th>

        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BloodGroup)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Create", new { Id = item.Id, item.Name, item.groupId, item.Address, item.Email, item.Mobile }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "DeleteDnr", new {item.Id }, new { @class = "btn btn-danger",onclick="return confirm('Are You Sure?')" })
            </td>

        </tr>
}
    </tbody>
</table>

DonorInformation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DonorInformation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DonorInformation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Donor" asp-action="DonorList">DonorInformation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DonorInformation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>